<?php

    require_once '../conf.php';
    require_once 'bll/PdfManager.php';
    
    $pdfManager = new PdfManager(2);
    
    $pdfManager->addRow(array(0 => 'kolumna 2', 1 => 'wartosc w kolumnie drugiej'));
    $pdfManager->addRow(array(0 => 'kolumna 3', 1 => 'wartosc w kolumnie trzeciej'));
    $pdfManager->addRow(array(0 => 'kolumna czwarta', 1 => 'wartosc w kolumnie czwartej to wyjatkowo dlugi text, taki, ktory na pewno musi ulec zlamaniu przez algorytm. ble bla ble'));
    $pdfManager->addRow(array(0 => 'kolumna 5', 1 => 'a co mi tam'));
    $pdfManager->addRow(array(0 => 'teraz zabawa sie odwraca', 1 => 'a co mi tam'));
    $pdfManager->addRow(array(0 => 'kolumna 5', 1 => 'a co mi tam'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 1, ktora jest dluzsza duzo wwww:::::', 1 => 'wartosc w kolumnie 1'));
    $pdfManager->addRow(array(0 => 'kolumna wwwwwwwWWWWWWwwM::::::::', 1 => 'wartosc w kolumnie wW'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi tu'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi woogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => array('a co mi wogle, hdqi 1ghdsfq wughuwgh fqegfwirh fuewg fewyuigvwegh ewughuwrgh erug rug rwug eruwg wurguwr', 'a co mi w szczegle')));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'inny text'));
    $pdfManager->addRow(array(0 => 'kolumna 6, ktorej zadaniem jest wykroczenie i zlamanie 1 kolumny, co do czego jestem absolutnie zdeterminowany', 1 => 'text bezposrednio przed,haha,  text bezposrednio przed, text bezposrednio przed, text bezposrednio przed, text bezposrednio przed'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi woglewwwwwwwwweeeeeeeeeeeeeeeeeeeeew wwwwwwwwwwwwwwwwwwwwweeeeeeeeeeeee wwwwwwwww wwwwwwwwwwwwwwwwwwww wwwwwwwwww'));
    
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'text bezposrednio po'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'tez inny text'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdfManager->addRow(array(0 => 'kolumna 6', 1 => 'a co mi wogle'));
    $pdf = $pdfManager->getPdf();
    $pdf->Output('test1.pdf');
    echo '<br /><br />ok<br /><br />';