INSERT INTO raport_agencja_pp ("nazwa") 
VALUES ('jmarek@eena.nl')
, ('mswart@eena.nl')
, ('rdabrowski@eena.nl')
, ('jzielezny@eena.nl')
, ('avandermeer@eena.nl')
, ('kdijkstra@eena.nl')
, ('lleijssenaar@eena.nl')
