UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Bytom';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Chorzów';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Dobrodzień';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Gliwice';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Jastrzębie Zdrój';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Jastrzębie Zdrój A. Bożka';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Katowice';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Kędzierzyn - Koźle';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Krapkowice';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Legnica';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Lubin';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Nowa Sól';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Olesno';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Opole';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Ozimek';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Polkowice';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Pszów';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Racibórz';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Rybnik';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Rydułtowy';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Strzelce Opolskie';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Toszek';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Wodzisław Śląski';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Wrocław';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Zabrze';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Zielona Góra';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Żory';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Pyskowice';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Nysa';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Grodków';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Częstochowa';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Praszka';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Kluczbork';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Lubliniec';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Głogówek';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Brzeg';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Tychy';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Prudnik';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Rzeszów';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Dębica';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Tarnów';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Brzesko';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Kraków';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Ropczyce';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Paczków';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Oława';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Strzegom';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Jawor';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Szprotawa';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Zamość';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Janów Lubelski';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Nisko';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Stalowa Wola';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Sandomierz';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Tarnobrzeg';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Mielec';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Chełm';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Lublin';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Kraśnik';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Ostrowiec Świętokrzyski';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Starachowice';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Puławy';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Radom';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Skarżysko-Kamienna';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Kielce';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Jędrzejów';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Szczekociny';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Zawiercie';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Tarnowskie Góry';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Sanok';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Krosno';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Jasło';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Biecz';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Gorlice';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Grybów';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Nowy Sącz';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Limanowa';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Mszana Dolna';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Myślenice';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Hrubieszów';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Tomaszów Lubelski';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Lubaczów';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Nowa Sarzyna';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Leżajsk';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Kolbuszowa';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Przemyśl';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Jarosław';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Przeworsk';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Bochnia';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Sucha Beskidzka';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Wadowice';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Andrychów';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Kęty';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Oświęcim';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Żywiec';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Pszczyna';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Bielsko-Biała';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Skoczów';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Wieluń';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Gorzów Śląski';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Otmęt';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Przywory';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Cieszyn';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Warszawa';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Łódź';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Zduńska Wola';
UPDATE msc_odjazdu SET strefa_id = 1 WHERE nazwa = 'Sieradz';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Kalisz';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Ostrów Wielkopolski';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Ostrzeszów';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Kępno';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Syców';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Oleśnica';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Złoty Stok';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Kłodzko';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Ząbkowice Śląskie';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Dzierżoniów';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Świdnica';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Wałbrzych';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Leszno';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Wschowa';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Głogów';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Izbicko';
UPDATE msc_odjazdu SET strefa_id = 2 WHERE nazwa = 'Jelenia Góra';
